name: Deploy OKE

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Create terraform.tfvars and oci key
        run: mkdir -p ~/.oci/
        run: echo '${{ secrets.OCI_KEY }}' > ~/.oci/oci_api_key_public.pem
        run: chmod 600 ~/.oci/oci_api_key_public.pem
        run: echo '${{ secrets.TFVARS }}' > terraform.tfvars
      
      - name: Terraform init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        run: echo ${{ steps.plan.outputs.stdout }}
        run: echo ${{ steps.plan.outputs.stderr }}
        run: echo ${{ steps.plan.outputs.exitcode }}
      
      - name: Terraform apply
        run: terraform apply -auto-approve